name: Conda publish

on:
  workflow_run:
    workflows: ["PyPI publish"]
    types: 
      - completed
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          conda install -y -c conda-forge -c defaults grayskull conda-build anaconda-client
          conda config --add channels conda-forge 
          conda config --set anaconda_upload yes
      - name: Generate conda recipe with GraySkull
        shell: bash -l {0}
        run: |
          grayskull pypi simple-mri

      - name: Build and upload conda package to Anaconda Cloud
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          conda build simple-mri --skip-existing
